# Example of Infrastructure as code
# Mark Alberton
#
# MAPPINGS
Mappings:
  "260036373721":
    us-east-1:
      VpcCidr: 172.16.0.0/17
      Az0PublicSubnet: 172.16.0.0/20
      Az0PrivateSubnet: 172.16.16.0/20
      Az1PublicSubnet: 172.16.32.0/20
      Az1PrivateSubnet: 172.16.48.0/20
      RegUc: US-EAST-1
      RegAbb: use1
    us-west-2:
      VpcCidr: 172.16.128.0/17
      Az0PublicSubnet: 172.16.128.0/20
      Az0PrivateSubnet: 172.16.144.0/20
      Az1PublicSubnet: 172.16.160.0/20
      Az1PrivateSubnet: 172.16.176.0/20
      RegUc: US-WEST-2
      RegAbb: usw2

# RESOURCES
Resources:

# ######################################## VPC

  VpcBase:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", VpcCidr ]
      EnableDnsSupport: True
      EnableDnsHostnames: True
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: VPC Test

# ######################################## INTERNET GATEWAY

  VpcIgw:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
        Value: VPC Test IGW

  VpcIgwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcBase
      InternetGatewayId: !Ref VpcIgw

# ######################################## SUBNETS

  Az0PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VpcBase
      CidrBlock: !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", Az0PublicSubnet ]
      AvailabilityZone: !Select [ 0, !GetAZs ]
      MapPublicIpOnLaunch: False
      Tags:
        - Key: Name
          Value: !Join [" ", [ !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", RegUc ], "Public Subnet" ] ]

  Az0PrivateSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VpcBase
      CidrBlock: !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", Az0PrivateSubnet ]
      AvailabilityZone: !Select [ 0, !GetAZs ]
      MapPublicIpOnLaunch: False
      Tags:
        - Key: Name
          Value: !Join [" ", [ !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", RegUc ], "Private Subnet" ] ]

  Az1PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VpcBase
      CidrBlock: !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", Az1PublicSubnet ]
      AvailabilityZone: !Select [ 1, !GetAZs ]
      MapPublicIpOnLaunch: False
      Tags:
        - Key: Name
          Value: !Join [" ", [ !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", RegUc ], "Public Subnet" ] ]

  Az1PrivateSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VpcBase
      CidrBlock: !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", Az1PrivateSubnet ]
      AvailabilityZone: !Select [ 1, !GetAZs ]
      MapPublicIpOnLaunch: False
      Tags:
        - Key: Name
          Value: !Join [" ", [ !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", RegUc ], "Private Subnet" ] ]


# ######################################## NAT GATEWAY

# ######################################## ROUTE TABLES

  RouteTablePublic:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VpcBase
      Tags:
      - Key: Name
        Value: VPC Test public RT

  RouteTablePrivate:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VpcBase
      Tags:
      - Key: Name
        Value: VPC Test private RT

# ######################################## ROUTES

  RouteTablePublicAddIgw:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref Igw
      RouteTableId: !Ref RouteTablePublic

# ######################################## SUBNET ASSOCIATIONS

  RouteTablePublicAssociateSubnetAz1:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref SubnetPublicAz1

  RouteTablePublicAssociateSubnetAz2:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref SubnetPublicAz2

  RouteTablePrivateAssociateSubnetAz1:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePrivate
      SubnetId: !Ref SubnetPrivateAz1

  RouteTablePrivateAssociateSubnetAz2:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePrivate
      SubnetId: !Ref SubnetPrivateAz2

# security groups
# acl
# vpn attachments
# network interfaces
# vpc peering
